### ISSUE TITLE
Coloca no GitHub Pages

### ISSUE THREAD

**Issue by Jeice01** [MarceloRodrigues1853/simulador-piano#1]
Olá, Marcelo!
Coloca no gitHub Pages para a gente testar o piano online. Beleza!

https://www.alura.com.br/artigos/como-colocar-projeto-no-ar-com-github-pages

**Comment by MarceloRodrigues1853** [comment]
sim professora é que estou implementando uma função do modo tutorial por
isso não tinha subido ainda

mas esta aqui o link :
https://marcelorodrigues1853.github.io/simulador-piano/

se a vc souber de algun link onde acho partituras para iniciantes me passa
por gentileza

Em sex., 17 de nov. de 2023 às 09:30, Jeice Santos ***@***.***>
escreveu:
